#!/bin/sh

ROOT=$(readlink -f root)
export ROOT

mkdir -p system root/bin/ root/proc/

for script in scripts/*; do
    $script
done

cd "$ROOT" && find . | cpio -o -H newc | gzip -9 > ../system/initrd.img
